BTtuan2/config/routes.rb
Rails.application.routes.draw do
 
  resources :users
 
  root 'welcome#index'
end

BTtuan2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

BTtuan2/app/models/user.rb
class User < ApplicationRecord
end

BTtuan2/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

BTtuan2/app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def create
    @user = User.new(user_params)
 
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def update
    @user = User.find(params[:id])
 
    if @user.update(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def destroy
      @user = User.find(params[:id])
      @user.destroy
  
      redirect_to users_path
   end
 
private
  def user_params
    params.require(:user).permit(:username, :password)
  end
end 

BTtuan2/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

BTtuan2/app/helpers/application_helper.rb
module ApplicationHelper
end

BTtuan2/app/helpers/users_helper.rb
module UsersHelper
end

BTtuan2/app/helpers/welcome_helper.rb
module WelcomeHelper
end

BTtuan2/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Login</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

BTtuan2/app/views/users/_form.html.erb
<%= form_for @user do |f| %>
 
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@user.errors.count, "error") %> prohibited
        this user from being saved:
      </h2>
      <ul>
        <% @user.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </p>
 
  <p>
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
 
<% end %>

BTtuan2/app/views/users/edit.html.erb
<h1>New user</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', users_path %>

BTtuan2/app/views/users/index.html.erb
<h1>Listing Users</h1>
<%= link_to 'New user', new_user_path %>
<table>
  <tr>
    <th>Username</th>
    <th>Password</th>
    <th colspan="3"></th>
  </tr>
 
  <% @users.each do |user| %>
    <tr>
      <td><%= user.username %></td>
      <td><%= user.password %></td>
      <td><%= link_to 'Show', user_path(user) %></td>
      <td><%= link_to 'Edit', edit_user_path(user) %></td>
      <td><%= link_to 'Del', user_path(user),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

BTtuan2/app/views/users/new.html.erb
<h1>New user</h1>
 
<%= render 'form' %>
 
<%= link_to 'Back', users_path %>

BTtuan2/app/views/users/show.html.erb
<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>
 
<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>
<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>	

BTtuan2/app/views/welcome/index.html.erb
<h1>Hello everyone!</h1>
<%= link_to 'This is My Blog', controller: 'users' %>